markdown: redcarpet
baseurl: ""
permalink: pretty
exclude:
  - 'deploy.sh'
  - 'rsync-exclude.txt'
  - 'npmupdatedev'
  - 'package.json'
  - 'README.md'
  - 'node_modules'
  - '*.styl'
  - '*.coffee'
  - '*.coffee.js'
  - 'cdn'
  - 'aws-s3.policy'

cdn: //17kp.s3-us-west-2.amazonaws.com
