markdown: redcarpet
baseurl: ""
permalink: pretty
exclude:
  - 'deploy.sh'
  - 'rsync-exclude.txt'
  - 'npmupdatedev'
  - 'package.json'
  - 'README.md'
  - 'node_modules'
  - '*.styl'
  - '*.coffee'
  - '*.coffee.js'

cdn: /img
